name: CI for DAGs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-dags:
    name: Test DAGs on MWAA Local Runner
    uses: t04glovern/mwaa-test-workflow/.github/workflows/action.yml@main
    with:
      dags_path: dags
      startup_script_path: startup.sh
      dag_id: dag_with_taskflow_api
      execution_date: 2024-10-09
