name: CI for DAGs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-dags:
    uses: t04glovern/mwaa-test-workflow@main
    with:
      dags_path: dags
      start_script_path: startup.sh
      dag_id: dag_with_taskflow_api
      execution_date: 2024-10-09
